import { Router } from "express";
import authRoutes from "./auth.routes";
import agendaRoutes from "./agenda.routes";
import plannerRoutes from "./planner.routes";
import notesRoutes from "./notes.routes";
import habitsRoutes from "./habits.routes";
import goalsRoutes from "./goals.routes";
import financeRoutes from "./finance.routes";
import projectsRoutes from "./projects.routes";
import notificationsRoutes from "./notifications.routes";
import todayRoutes from "./today.routes";
import searchRoutes from "./search.routes";
import syncRoutes from "./sync.routes";
import linkPreviewRoutes from "./linkPreview.routes";
import scheduleRoutes from "./schedule.routes";
import customPagesRoutes from "./customPages.routes";
import calendarLegendRoutes from "./calendarLegend.routes";
import eventCategoryRoutes from "./eventCategory.routes";
import googleCalendarRoutes from "./googleCalendar.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/agenda", agendaRoutes);
router.use("/planner", plannerRoutes);
router.use("/notes", notesRoutes);
router.use("/habits", habitsRoutes);
router.use("/goals", goalsRoutes);
router.use("/finance", financeRoutes);
router.use("/projects", projectsRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/today", todayRoutes);
router.use("/search", searchRoutes);
router.use("/sync", syncRoutes);
router.use("/link-preview", linkPreviewRoutes);
router.use("/schedule", scheduleRoutes);
router.use("/custom-pages", customPagesRoutes);
router.use("/calendar-legend", calendarLegendRoutes);
router.use("/event-categories", eventCategoryRoutes);
router.use("/integrations/google", googleCalendarRoutes);

export default router;
